-- Migración 004: Tabla de Empresas / Comercios
CREATE TABLE IF NOT EXISTS `empresas` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `usuario_id` INT UNSIGNED NOT NULL,
    `nombre` VARCHAR(150) NOT NULL,
    `rif` VARCHAR(30) NULL,
    `categoria_id` INT UNSIGNED NOT NULL,
    `descripcion` TEXT NULL,
    `telefono` VARCHAR(30) NULL,
    `correo_contacto` VARCHAR(150) NULL,
    `direccion` TEXT NOT NULL,
    `zona` VARCHAR(100) NOT NULL,
    `latitud` DECIMAL(10, 8) NULL,
    `longitud` DECIMAL(11, 8) NULL,
    `logo_url` VARCHAR(255) NULL,
    `redes_sociales` JSON NULL,
    `estado` ENUM('pendiente', 'aprobado', 'rechazado') NOT NULL DEFAULT 'aprobado',
    `destacado` TINYINT(1) NOT NULL DEFAULT 0,
    `calificacion` DECIMAL(2, 1) NOT NULL DEFAULT 5.0,
    `total_resenas` INT UNSIGNED NOT NULL DEFAULT 0,
    `rango_precio` ENUM('$', '$$', '$$$') NOT NULL DEFAULT '$$',
    `delivery` TINYINT(1) NOT NULL DEFAULT 0,
    `abierto` TINYINT(1) NOT NULL DEFAULT 1,
    `verificado` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_empresas_usuario` (`usuario_id`),
    INDEX `idx_empresas_categoria` (`categoria_id`),
    INDEX `idx_empresas_zona` (`zona`),
    INDEX `idx_empresas_estado` (`estado`),
    CONSTRAINT `fk_empresas_usuario` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_empresas_categoria` FOREIGN KEY (`categoria_id`) REFERENCES `categorias` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
